linters:
  enable-all: true
  disable:
    - copyloopvar
    - intrange
    - depguard
    - execinquery
    - exhaustruct
    - exportloopref
    - gochecknoglobals
    - gci # https://github.com/golangci/golangci-lint/issues/1490
    - godot
    - gomnd
    - ireturn
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl
    - zerologlint

linters-settings:
  cyclop:
    max-complexity: 20
    package-average: 10
  dupl:
    threshold: 100
  funlen:
    lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
    statements: 50
  gocognit:
    min-complexity: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - unnamedResult
  godox:
    keywords:
      - FIXME
  lll:
    line-length: 140
  mnd:
    ignored-functions:
      - '^v\.SetDefault'
  misspell:
    locale: US
    ignore-words:
      - "importas" # linter name
  nestif:
    # Minimal complexity of if statements to report.
    # Default: 5
    min-complexity: 10
  nlreturn:
    block-size: 3
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped
  paralleltest:
    # Ignore missing calls to `t.Parallel()` and only report incorrect uses of it.
    # Default: false
    ignore-missing: true
    # Ignore missing calls to `t.Parallel()` in subtests. Top-level tests are
    # still required to have `t.Parallel`, but subtests are allowed to skip it.
    # Default: false
    ignore-missing-subtests: true
  revive:
    rules:
      - name: indent-error-flow
      - name: unexported-return
        disabled: true
      - name: unused-parameter
      - name: unused-receiver

output:
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false
  show-stats: true
  sort-results: true
  sort-order:
    - file
    - linter
    - severity

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  whole-files: true
