name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  go-mod:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum
  golangci-lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.23"
      - name: lint
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            golangci/golangci-lint:latest \
            golangci-lint run --fix --config /app/.golangci.yml ./...
